# Generated by Django 4.1.7 on 2023-03-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=10)),
                ('cuil', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Minorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('medio_de_pago', models.CharField(max_length=35)),
                ('nombre_comprador', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=5)),
                ('quien_retira', models.CharField(max_length=50)),
            ],
        ),
    ]
